# -*- coding: utf-8 -*-
"""DAY04_PRACTISE_TEST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18iDx6G9p6UZKaAZUZgIjNG05c5vUa4Br

QN1. Write an interactive Python Program to implement “Guess Game"
"""

secretNumber=3
guess=int(input("Guess a number between 1 and 10 "))
while True:
  if secretNumber==guess:
    print("Congratulations! You guessed the number correctly!")
    break
  elif secretNumber<guess:
    print("Too high! Try again.")
    guess=int(input("Guess a number between 1 and 10 "))
  else:
    print("Too low! Try again.")
    guess=int(input("Guess a number between 1 and 10 "))
  continue

"""QN2. Write a program to find and print the Factorial of this number. The Factorial of a positive integer N refers to the product of all number in the range from 1 to N."""

num=int(input("enter the number: "))
prod=1
for i in range(1,num+1):
  prod=prod*i
print(prod)

"""QN3. Profile Picture size calculator"""

W = float(input("width of the photo"))
H = float(input("Height of the photo"))
L = float(input("enter the minimum dimension"))
while True:
  if H<L or W<L:
    print("UPLOAD ANOTHER")
    W = float(input("width of the photo"))
    H = float(input("Height of the photo"))
  elif H==L and W==L:
    print("ACCEPTED")
    break
  else:
    print("CROPIT")
    W = float(input("width of the photo"))
    H = float(input("Height of the photo"))
  continue